import { MODULE_NAME } from './../constants';

export const GET_PORTFOLIO_LIST = `${MODULE_NAME}/GET_PORTFOLIO_LIST`;
export const GET_PORTFOLIO_LIST_SUCCESS = `${MODULE_NAME}/GET_PORTFOLIO_LIST_SUCCESS`;
export const GET_PORTFOLIO_LIST_ERROR = `${MODULE_NAME}/GET_PORTFOLIO_LIST_ERROR`;

export const GET_FILTER_LIST = `${MODULE_NAME}/GET_FILTER_LIST`;
export const GET_FILTER_LIST_SUCCESS = `${MODULE_NAME}/GET_FILTER_LIST_SUCCESS`;
export const GET_FILTER_LIST_ERROR = `${MODULE_NAME}/GET_FILTER_LIST_ERROR`;
